name: Ubuntu 22.04 Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v1
    - name: build
      run : |
        sudo apt install cmake libusb-1.0-0 libusb-1.0-0-dev      
        cmake -S.
        make
